services:
  - type: web
    name: superset
    env: docker
    repo: https://github.com/apache/superset # Upewnij się, że to link do Twojego forka
    plan: free # Użycie darmowego planu
    healthCheckPath: /health
    envVars:
      - key: SQLALCHEMY_DATABASE_URI
        fromDatabase:
          name: superset-db # Upewnij się, że to nazwa Twojej bazy danych w Render
          property: connectionString
      - key: SUPERSET_SECRET_KEY
        generateValue: true # Render automatycznie wygeneruje bezpieczny klucz
    buildCommand: |
      pip install psycopg2-binary && \
      superset fab create-admin --username admin --firstname Admin --lastname User --email admin@example.com --password test123456 && \
      superset db upgrade && \
      superset init
    startCommand: "gunicorn --bind 0.0.0.0:$PORT --access-logfile - --error-logfile - --workers 3 --worker-class gthread --threads 8 'superset.app:create_app()'"
